### ISSUE TITLE
horceracing

### ISSUE THREAD

**Issue by sczin** [sczin/BlockFive#3]

**Comment by kevindeslauriers** [comment]
![error](https://cloud.githubusercontent.com/assets/739858/6127902/30477f00-b0fe-11e4-8a1c-b643d9e2465d.JPG)


Excellent Work - 

Excellent use of methods and arrays. I like the photo finish.

I have included a screenshot of an error I had when performing a photo finish.
Your code is very well written and organised.  98%

**Comment by sczin** [comment]
Fixed the error. Closing a scanner caused that.
